settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: go-graphql-api
  path: ./cmd/
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - ../
    ignored_paths:
    - .git
    - .realize
    - vendor
